### ISSUE TITLE
res/ not installed

### ISSUE THREAD

**Issue by AssociationSirius** [namelessvoid/qrwar#107]
This is not a bug but I warn you that the directory res is created when you unzip the file but it is empty. (which is normal because the data is in another archive)

You have to download the data archives and install them in the res directory.

If we click on the directory **res @ 1407295** we get a page "not found error 404".

Could you just mention it in the readme file?

**Comment by namelessvoid** [comment]
> If we click on the directory res @ 1407295 we get a page "not found error 404".

Once again I've forgotten to push the submodule as well. I just fixed it.

**Comment by namelessvoid** [comment]
So I decided to get rid of the submodule and include the resources into the main repository directly. Now, there is no need to download / checkout the resources separately.

The initial idea behind excluding the resources was to allow for others to provide custom tilesets. This however can be done in a better way anyways.

**Comment by AssociationSirius** [comment]
If you focus on the code, I think it's a good idea to merge.
If then the amount of additional data explodes, returning to a separate
source would be more convenient.

Le mer. 7 nov. 2018 à 20:02, Simon Kerler <notifications@github.com> a
écrit :
