### ISSUE TITLE
Qrwar crash -- no map --

### ISSUE THREAD

**Issue by AssociationSirius** [namelessvoid/qrwar#108]
The first time I run the game and click on new match, the program crashes because there is no map in the USER / .qrwar directory

Same if I delete the cards already created.

**Comment by namelessvoid** [comment]
Those two commits fix the crash. Two more things I'd like to do. When no map is present

- [ ]  the MapPreview renders as a white square. Either display nothing or a message indicating missing maps.
- [ ]  a generic "the selected map could not be loaded" message is prompted when you click "begin skirmish". A more specific message "no maps are present" should be displayed instead.

**Comment by namelessvoid** [comment]
Update: When the skirmish preparation is entered but no maps are available, the GUI is hidden and only a error message is displayed: 

![image](https://user-images.githubusercontent.com/1771470/48023906-69dbc580-e13f-11e8-832f-2ff9f077362c.png)
